
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8


org.gradle.parallel=true
org.gradle.configureondemand=true


android.defaults.buildfeatures.buildconfig=false
android.nonTransitiveRClass=true


android.enableComposeCompilerReports=false
android.enableComposeCompilerMetrics=false


android.useAndroidX=true
android.enableJetifier=true


kotlin.code.style=official
kotlin.incremental=true


org.gradle.daemon=true


org.gradle.workers.max=4

org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
